### ISSUE TITLE
New plants not Growing?

### ISSUE THREAD

**Issue by krovex101** [Voxel-Friend/RusticThaumaturgy#16]
Hi,
I have created and planted shimmer bulbs and cinders but they never seem to grow. tried using bonemeal and the growth lamp but to no avail!
please can you help, am i doing something wrong or is this a bug?
thanks

**Comment by Voxel-Friend** [comment]
Hmm. Ill give it a look. I use the same logic as Ender Crops, minus a few things. I'll try that fix. Have to reset my dev environment though so might be a few days.

**Comment by Voxel-Friend** [comment]
If I understand correctly, this would currently mean the crops only grow in the dark. Interesting thought.

**Comment by wamc2017** [comment]
Ender Crops uses an additional lightcheck if the plants can grow:
https://github.com/DrManganese/ender-crop/blob/c57833a5e986e3e0f40ee630bfb2d28a60883d24/src/main/java/io/github/drmanganese/endercrop/block/BlockCropEnder.java#L74

The problem is, if the lightlevel is 7 or lower with the current code, the plants can grow, but after the block update, the seeds pop out like vanilla crops...
So either you change it to >=7 or you do the additional check like in Ender Crops. (I personally would prefer if the plants can grow on higher lightlevels, but that's your decission. ;))

**Comment by Voxel-Friend** [comment]
Ah, that would explain it then. So, in your preference, just switch to > = 7?

**Comment by Voxel-Friend** [comment]
Decided to tackle this right away, after all btw. Shouldn't be too hard to get set back up.

**Comment by Voxel-Friend** [comment]
Ok, @wamc2017 @krovex101  if you two are willing, could one or both of you test this build out and see if there is anything else needing fixed? Please test as many ways to accelerate growth as you can. It seems to work fine for me.

[Rustic Thaumaturgy-2.6(test).jar.zip](https://github.com/Voxel-Friend/RusticThaumaturgy/files/2591341/Rustic.Thaumaturgy-2.6.test.jar.zip)

**Comment by wamc2017** [comment]
I tested Actually Additions worms, Agricrafts sprinkler, Astral Sorcerys colored lens (growth), Blood Magics ritual of the green grove, Botanias agricarnation, Cyclics sprinkler, Extra Utilities watering can, Mystical Agricultures watering cans, Not Enough Wands acceleration wand, Open Blocks sprinkler, Tiny Progressions growth crystals and watering can and Tocherino, all worked fine!

**Comment by krovex101** [comment]
awesome will try it in a bit, but looks like @wamc2017 has beat me to it ;-)

**Comment by Voxel-Friend** [comment]
No need @krovex101, I trust wamc's testing. I'll go ahead and release. Stay tuned!

**Comment by Voxel-Friend** [comment]
Uploaded and awaiting approval. Thanks again for your guys' help!
